site_name: gameserver.tech
site_url: https://gameserver.tech/
site_description: gameserver.tech - Egg & Image Collection for Pelican/Pterodactyl Gameserver Panel
site_author: gOOvER

repo_url: https://github.com/gsrvtech/website
repo_name: Improve this page
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 <a href="https://github.com/gOOvER">gOOvER</a>. - <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  locale: en

  # Fonts für modernen Look
  font:
    text: Roboto
    code: Roboto Mono

  # Icons
  icon:
    edit: material/pencil 
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
      - tabs
      - instant
      - content.code.annotate
      - content.action.edit
      - content.action.view
      - content.code.copy
      - content.tabs.link
      - navigation.footer
      - navigation.indexes
      - navigation.instant
      - navigation.instant.progress
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      #- toc.integrate
  
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Customization
extra:
  homepage: https://goover.dev/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gameservertech
    - icon: fontawesome/brands/discord
      link: https://discord.goover.dev

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage 

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: gsrvtech
      repo: website
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - tooltips
  - charts
  - pdf-export
  - open-in-new-tab
  - autolinks
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  
  - blog:
      blog_toc: true
      post_readtime: false
      archive: true
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      categories: false
      categories_name: Categories
      authors: false
      draft: true

  - social:
      cards: true

 # - minify:
 #     minify_html: true
 #     minify_js: true
 #     minify_css: true
 #     htmlmin_opts:
 #     remove_comments: true
      
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Vienna
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true

# Page tree
nav:
  - Home: index.md
  - Eggs: eggs/index.md
  - Images: 
    - images/index.md
    - Java Images: images/java/index.md
    - SteamCMD Images: images/steamcmd/index.md
    - NodeJS: images/nodejs/index.md
  - Scripts: scripts/index.md
  - Support: support.md
  - License: license.md 
